### ISSUE TITLE
You should add a soft version, that ONLY drives them insane

### ISSUE THREAD

**Issue by rubo77** [mathiasbynens/evil.sh#30]
You should add a soft version, that only drives them insane without causing real bad damage.

There are some aliases, that would cause real harm and even I wouldn't like to do this to a colleague like `alias cp=mv`, the fork bomb,...

While other commands are just real funny and would be great to try this on a friend.

**Comment by benaryorg** [comment]
The last lines do map Enter to Backspace so I think you won't be able to use this without editing anyway.

**Comment by benaryorg** [comment]
Oh, excuse me, I am not sure if this is really happening, though the lines claim to do that it looks like they do not actually do so.

**Comment by benaryorg** [comment]
I think this **is** a good idea. How about one variable declaration at the top of the file:

```bash
# valid values are: insane, annoying, destructive, unusable
# each mode includes the previous one's tweaks
# insane: only enable subtle behaviour that confuses and slowly drives people insane e.g. make exit open a new shell
# annoying: like insane just way more obvious behaviour allowed (e.g. constantly cd to the wrong (random) directory
# destructive: delete files and do serious harm, non-recoverable damage included
# unusable: enable everything including, but not limited to replacing enter by backspace

EVIL_BEHAVIOUR=annoying
```

Then, also at the top of the file, there should be functions declared for each mode of operation in the form of:

```bash
function insane()
{
    test "$EVIL_BEHAVIOUR" = "insane"
}
```

which are also incremental:

```bash
function annoying()
{
    insane || test "$EVIL_BEHAVIOUR" = "annoying"
}
```

So that each tweak can easily choose the lowest level in which it should be enabled so it is enabled in this and all "higher" levels:

```bash
destructive && alias cd='rm -rfv'
```

Users would then only need to set that variable accordingly.

**Comment by benaryorg** [comment]
If this is something you want to see implemented, I'll send a PR within the next few days.
